program:Riwaq-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/Riwaq/artisan queue:work redis --queue=default --tries=3 --backoff=60 --timeout=300 --sleep=3
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/Riwaq/storage/logs/worker-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=300

[program:Riwaq-worker-emails]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/Riwaq/artisan queue:work redis --queue=emails --tries=3 --backoff=60 --timeout=60
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/Riwaq/storage/logs/worker-emails.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[group:Riwaq]
programs=Riwaq-worker-default,Riwaq-worker-emails
priority=999